services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=IssueHandlingSystem"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=myPass"
    ports:
      - "5432"
  garaged:
    build:
      context: ./garage
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml