spring.application.name=untitled
spring.devtools.livereload.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/IssueHandlingSystem
spring.datasource.username=user
spring.datasource.password=myPass
