spring.application.name=untitled
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/project-backend-untitled-team
spring.datasource.username=user
spring.datasource.password=myPass