spring.application.name=untitled
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=1800000
spring.devtools.livereload.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/IssueHandlingSystem
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
s3.endpoint=http://127.0.0.1:3900
s3.region=garage
s3.access-key=GKa20e76d888951a2065622297
s3.secret-key=bf2d16c8ceb6c326120cb3fd8e3c0414259cd0406041c258b4b6eeb3218e6468
logging.level.software.amazon.awssdk.request=DEBUG
logging.level.software.amazon.awssdk.auth.signing=DEBUG
